### ISSUE TITLE
Feature Request - Sorting results in Pandora's Box by ID/SID

### ISSUE THREAD

**Issue by Santhosh-CP** [Admiral-Fish/RNGReporter#10]
Hello!

While trying to Gen4 RNG using Pandora's Box's Shiny PID seed finder, we get various seeds with various TID & SIDs. I was wondering if it was possible to implement a sort the resultant seeds according to TID or SID by clicking on the column name. Just like how it works in Time Finder. It will be easier to find a more desirable TID when we can search in an sorted manner. 

Thanks!

**Comment by Admiral-Fish** [comment]
I'll look into when I have time.

**Comment by Admiral-Fish** [comment]
Thoughts on doing it for 5th gen as well?

**Comment by Santhosh-CP** [comment]
Yup it will be useful for Gen5 too! Thanks! :D

**Comment by Admiral-Fish** [comment]
Should be good. Let me know if there are any problems with the sorting

**Comment by Santhosh-CP** [comment]
I will try it out when the next release is out. Thank you very much~!

**Comment by Admiral-Fish** [comment]
Or download the latest commit from here https://ci.appveyor.com/project/Admiral-Fish/rngreporter/build/artifacts . Probably won't publish a new release for quite some time still.
