### ISSUE TITLE
Suggestion - TID / SID profile list

### ISSUE THREAD

**Issue by RichardPaulAstley** [Admiral-Fish/RNGReporter#16]
Hi,

Maybe it's a stupid request but well, I can try. 

Could it be possible to have a little place to put ALL the TID / SID with the right game and so the right Generation. This way people could just load a list in the Time Finder with the corresponding generations. And on the main menu every TID / SID would be available.

Really usefull for little minds like me T-T

Thanks o/

**Comment by Admiral-Fish** [comment]
Seems like an interesting idea. Little more time consuming then the time left I am putting into Reporter. Feel free to make this issue on PokeFinder.
