### ISSUE TITLE
Suggestion - Pokemon Box Eggs RNG

### ISSUE THREAD

**Issue by OPBreloom** [Admiral-Fish/RNGReporter#17]
I wanted to see if it's possible to RNG Pokemon Box Egg, for IVs, since there's a way to make it Shiny via TID/SID RNG Abuse within the PID of the egg, if so can you do make a guide/program for it, thank you!

**Comment by Admiral-Fish** [comment]
The tools needed to RNG are already built in(GameCubeRNG/IVs to PID). Just need to wait on Dolphin to get more reliable RTC manipulation before more can be done. Out of my hands.
