### ISSUE TITLE
Shiny ID Question or Bug

### ISSUE THREAD

**Issue by Odaxis** [Admiral-Fish/RNGReporter#19]
Hi there. I'm probably opening this in error. If so feel free to close it.

I'm trying to generate a Legit Shiny Manaphy from the Pokémon Ranger game with PKHeX. I can use your tool to get a proper PID for a Non shiny Manaphy, as soon as i use the SID provided along with the PID the Manaphy, Providing PKHeX is correct, shows as illegal.

Is there something special I need to do that I'm not doing to get a proper shiny value?

**Comment by Admiral-Fish** [comment]
Control click the illegal symbol and post a screenshot of it here.

**Comment by Odaxis** [comment]
1st the legal one, no errors
![image](https://user-images.githubusercontent.com/18354599/27841537-f6ccec88-60dc-11e7-96f4-04e596626c7e.png)

Second one with the SID for the used PID and the error
![image](https://user-images.githubusercontent.com/18354599/27841568-2afdffec-60dd-11e7-9bf9-a0112e4147d7.png)

**Comment by Admiral-Fish** [comment]
Encounter Type PID mismatch typically means the IVs don't match the PID. What IVs and PID do you have?

**Comment by Odaxis** [comment]
PID 6937DA48
IV's 31/31/31/31/31/31
Modest nature

**Comment by Admiral-Fish** [comment]
Not sure really. Would need the pkm file to test further.

**Comment by Odaxis** [comment]
Here you go. It's non shiny and legal as is. It's not until i insert a shiny ID for the PID that it becomes illegal
[Manaphy.zip](https://github.com/Admiral-Fish/RNGReporter/files/1123201/Manaphy.zip)

**Comment by Odaxis** [comment]
Also not sure if it will help. Here is the wondercard i based it off of.
[Manaphy Egg.zip](https://github.com/Admiral-Fish/RNGReporter/files/1126417/Manaphy.Egg.zip)

**Comment by Admiral-Fish** [comment]
Not really sure. This is probably a issue better for PKHeX since I'm really sure how the legality check works.
