### ISSUE TITLE
FRLG/E Pandora's Box shows wrong frames

### ISSUE THREAD

**Issue by Real96** [Admiral-Fish/RNGReporter#2]
I compared your Pandora's Box of FRLG/E with [this](https://github.com/hourglasseye/gen3tidsidframefinder) app. Pandora's Box shows wrong frame as you can see in [here](http://i.imgur.com/9fK0IYl.png). In the image the error is -3748 frames, but it changes for every TID. I also tried to get the correct SID with both apps frames to confirm this error

**Comment by Admiral-Fish** [comment]
It's not that is shows wrong frames. It's just that it only uses the TID when moving forward. I don't have a field for the PRNG state so anytime you use that tool with a PRNG state that isn't the TID it will be off since I don't account for any forward advances that don't start from the TID.

**Comment by Real96** [comment]
So how can be used the pandora's box?

**Comment by Admiral-Fish** [comment]
In it's current state it's really only used to find the frame that will get you the target SID. Although I suppose I can make it more like the other tool to make it more RNG friendly.

**Comment by Real96** [comment]
It would be great! :)

**Comment by Admiral-Fish** [comment]
I'll try to have it done by next week.

**Comment by Admiral-Fish** [comment]
Will implement this feature in my new RNG program I am making.

**Comment by Real96** [comment]
bad boy
