### ISSUE TITLE
Allow Seed to Time and Search Flips windows (presumably more windows) to be resized.

### ISSUE THREAD

**Issue by Storm-Eagle20** [Admiral-Fish/RNGReporter#20]
http://i.imgur.com/GBBl438.jpg

As of currently, my computer has an issue where the windows are not properly sized and they cannot be resized in any way. They must also be closed using the taskbar. This issue was also present in Slashmolder's RNG Reporter.

I was going to fork this and fix it then request a merge, but I don't know C#, only C and C++. I can do some testing to see if any other windows need this fix, but I'm fairly certain only Seed to Time and Search Flips are the only ones.

**Comment by Admiral-Fish** [comment]
Are you on windows or mac or linux?

Edit: and which version of the OS

**Comment by Storm-Eagle20** [comment]
Windows 7.
