### ISSUE TITLE
[Gen 3] Fishing Encounter Slots (Super Rod)

### ISSUE THREAD

**Issue by RichardPaulAstley** [Admiral-Fish/RNGReporter#21]
Well, after the long conversation of yesterday, i've decided to check a little more. Here I'll post things i'm 100% sure of. And this will help to make things clear.

For the reminder, I'm opening this since i had issues a long time ago with a Shiny Dragonair, you can find the post here : https://www.reddit.com/r/pokemonrng/comments/65v1rv/little_problem_with_super_rod_rng_on_fire_red/

And i've retried since, I'm having the same issue in any route. So for the moment : 

- Slot 3 and 4 in Pokemon Games are set in the Encounter Slot 4. Aka if you search for Encounter Slot 4 in RNG Reporter, you'll have the 3 & 4 Pokemon, and no way to predict which one you'll fish.

I'll edit if I can find more things.

**Comment by Admiral-Fish** [comment]
So the range needs to change to make slots 3 and 4 only slot 4?

**Comment by RichardPaulAstley** [comment]
No a lot of things are wrong but I told you, I can't find any pattern of the real generation, and it's near to impossible to do it with one VBA and nothing more.

But on ALL my test, Encounters slots 3 and 4 in game are set in the Encounter slot 4. 

But in some routes you'll have the Encounter slot 3 in the Encounter slot 3 in RNG Reporter or it'll give only Encounter slot 2 etc etc everything is not set correctly at all, and changes it seems.

**Comment by Admiral-Fish** [comment]
So basically it's all over the place?

**Comment by RichardPaulAstley** [comment]
Oups just saw that sorry x_x
So. For the Encounter Slot 4 yes, it's messy in every route i've tried, 100% of the time.

**Comment by Admiral-Fish** [comment]
Feel free to open this issue on PokéFinder but I'm gonna go ahead and close it on here.
