### ISSUE TITLE
Gen 5 Time Finder IV Frame Offset?

### ISSUE THREAD

**Issue by ShinySylveon04** [Admiral-Fish/RNGReporter#22]
RNG Reporter Version 10.3.2

In Gen 5 Time Finder for Stationary I'm searching for IV frames for B2 entralink RNG, and when I paste the seeds into the Main Window the IV frames are sometimes different than those given from Time Finder. When searching for seeds with no keypresses the IV frames both match up and after capturing the Pokemon are all correct ingame as well. However, when searching with one keypress some of the frames are not matching up between Time Finder and Main Window. The Main Window IV frames match to those ingame after capturing the Pokemon, so those can be assumed to be correctly predicted. 

![](https://cdn.discordapp.com/attachments/308023267266920458/404031932465283073/unknown.png)
- IV frames are not matching up between Time Finder and Main Window, however ingame the Main Window IV frames given seem to be correct

![](https://cdn.discordapp.com/attachments/308023267266920458/404038623780929536/unknown.png)
- Same seed as above with the IV frames being 5 and 6 instead of what was given in Time Finder

![](https://cdn.discordapp.com/attachments/308023267266920458/404042649830424586/unknown.png)
- IV frames match between Time Finder and Main Window for no keypresses

I searched for 1 keypress and so far those with Start, Select, L, and Right are wrong. Y, B, and Down are correct. 

The other day I used the same build to RNG a wild Ditto with keypresses and IV frame advancements and that was perfect, so not sure if the issue is just with Stationary or not.

Thanks fish for whenever you can look into this <3

**Comment by Admiral-Fish** [comment]
rip hash tables 27-30

**Comment by Admiral-Fish** [comment]
Fixed by 17c82f7

Forgot to include in commit message
