### ISSUE TITLE
Problem with PID-IV relation

### ISSUE THREAD

**Issue by Andyta2016** [Admiral-Fish/RNGReporter#23]
I have a problem when I calculate while breeding. The IVs in the game are different on the reporter
![Sin título](https://user-images.githubusercontent.com/22484314/54327631-cd3b9f80-45d8-11e9-9fad-8744303c8c02.png)

**Comment by Admiral-Fish** [comment]
Looks like you hit an alternate spread. https://gyazo.com/a76d4e6cd5fd83aeec2c2e57b4d69a2f

See https://github.com/Admiral-Fish/PokeFinder/issues/62 for more information. I would suggest using PokeFinder as I no longer work on RNG Reporter
