### ISSUE TITLE
'System.OutOfMemoryException' Error when searching through (very) high frames

### ISSUE THREAD

**Issue by LegoFigure11** [Admiral-Fish/RNGReporter#3]
http://i.imgur.com/0pvW09G.png

So this happened when I was searching for 31/x/31/31/31/31 Method 1 Spreads in the main window.
Full details of the error are [here](http://pastebin.com/zw7zmYGD).

**Comment by Admiral-Fish** [comment]
That's not really a bug per say. Your computer ran out of RAM to store the result. If I'm not mistaken you put 650 million for upper frame. I've only ever done 90 million max.

**Comment by LegoFigure11** [comment]
Hm, I never had this issue with 9.96.6 (managed to search up to 1B before).
It was probably just my computer having a bad day though, so I'll go ahead and close this. Thanks!
