### ISSUE TITLE
Colo/XD Pandora's Box discrepancies

### ISSUE THREAD

**Issue by LegoFigure11** [Admiral-Fish/RNGReporter#5]
[As discussed briefly on IRC](https://pastebin.com/raw/KfnfycWW "Logs of that conversation"), here are the discrepancies that I noticed in the Colo/XD Pandora's Box while attempting to RNG a TID/SID in European Colo. 

Right Click Issue
![alt text](http://i.imgur.com/sIxWmy0.png) ![alt text](http://i.imgur.com/q8d1wd9.png)
(Exact details of the error can be seen [here](https://pastebin.com/raw/CSVTPncv))

Hover Text Issue (https://github.com/Admiral-Fish/RNGReporter/blob/master/RNGReporter/Pandora.Designer.cs#L1037)
![alt text](http://i.imgur.com/K8eCggb.png) 
![alt text](http://i.imgur.com/NSxNl7E.png)

Another thing I noticed was this (and it may potentially be entirely user error on my part due to me not knowing how to properly use the program, but as far as I can work out it's not me).
![alt text](http://i.imgur.com/ATRS6CG.png)
After a great deal of trial and error, I managed to get my IDs to generate on the target frame (see frame = 0). However, I was not rewarded with the correct IDs! Instead of getting TID: 40687 SID: 11775 like the program says I should, I got TID: 19703 SID: 02839. I cross-checked this with [this tool](https://github.com/FishamanP/PokeGC-TIDTool/releases) which told me I needed to do two more advances, but this unfortunately advanced me past my target (pretty sure I got a 6 frame advancment instead of a 2 frame advancment).  But yeah, like I said - not sure if this is an issue with my procedure or with your tool, but it could be worth looking into regardless. Thanks!

**Comment by Admiral-Fish** [comment]
Will be fixed alongside #2
