### ISSUE TITLE
Entralink Ecounter Typer error

### ISSUE THREAD

**Issue by Real96** [Admiral-Fish/RNGReporter#6]
The Entralink Encounter Type search shows wrong nature frames (+2 for all pokemon, +1 for Arceus) and the PIDs are wrong

**Comment by Admiral-Fish** [comment]
Commit e9ef0d6 partially fixes this. PID should be correct for all PIDs (ex. 0x123456XX besides the XX which depends on the gender of the pokémon which requires testing). Nature should be accurate for Male only but needs testing for all other gender cases.
