### ISSUE TITLE
Colo/XD Main window bug

### ISSUE THREAD

**Issue by LegoFigure11** [Admiral-Fish/RNGReporter#9]
The last 4 rows in any given Colo/XD Main window search seem to be bugged, replacing the PID 16bit low of the 4th last row and all of the PID for the last 3 rows to be replaced with 0's. It also sets the SpA, SpD and Spe IVs of the last row to 0, and changes all of the gender ratios to be F.

Example can be seen here:
![alt text](http://i.imgur.com/T63E39J.png)
![alt text](http://i.imgur.com/qE8FlaA.png)

**Comment by Admiral-Fish** [comment]
Is this only gales/Colo? What about other methods?

**Comment by LegoFigure11** [comment]
All other methods appear to generate normally.
